Fixes for hard coded US dates (#1436)
* hard_coded_dates_all changes squashed in

* Fixed strftime formatting problems

* Fixed 'date_format' typo

* removed .date() method from date fields being formatted with the date_format() method

* removed .date() method from date fields being formatted with the date_format() method

* removed .date() method from date fields being formatted with the date_format() method

* replace DATE_FORMAT with SHORT_DATE_FORMAT

SHORT_DATE_FORMAT is a better replacement for '%m-%d-%Y'

* Removed superfluous unicode string prefix

* Removed all strftime usage and related format constants in settings.py.

All date/time formatting now done using date/time format localisations in settings.py

* fix date_format not defined (in build_ical_html)

* adjust settings to fix error messages on event add

* Enter a valid time.
* Please enter a valid Start Date/Time.

* remove duplicate setting USE_TZ

The USE_TZ is set to False by default. See commit https://github.com/tendenci/tendenci/commit/7237e53e84304f97755053df24ccd9016e9e41b9, and changelog https://github.com/tendenci/tendenci/blob/main/CHANGELOG.md#1615-2026-6-11 for reasons.

* Fixed naive datetime value error

* Removed duplicated class definition

* More hard-coded date formatting found and replaced with appropriate settings.{SHORT_}DATE{TIME}_FORMAT constants

* adjust to better match with the original formats

* Fixed isinstance type error

* Removed superfluous .date attribute

* Deleted accidentally duplicated line

* Removed redundant LONG_DATE_FORMAT

* Removed redundant .date() method, updated to f-string formatting for clarity and changed date_format method argument to the string that Django expects

* Found and fixed another hard-coded date/time format

* Corrected django.util.formats.date_format format strings
Also replaced django.template.defaultfilters.date imports with django.util.formats.date_format for consistency

* Added @deprecated flags to some filter functions that probably can be replaced by built-in Django equivalents

* Converted references to settings.SHORT_DATE_FORMAT to the equivalent strings

* TypeError at /events/add/ when All Day is checked

combine() got an unexpected keyword argument 'zoneinfo'

* RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware

* fix: localtime() cannot be applied to a naive datetime

* adjust date formats in theme migrations 002

* remove the settings DATE_INPUT_FORMATS and DATETIME_INPUT_FORMATS

Using django's default values is fine, or you can override them in your formats.py file with the setting FORMAT_MODULE_PATH. See https://docs.djangoproject.com/en/5.2/ref/settings/#format-module-path

---------

Co-authored-by: Jenny Qian <jqian@tendenci.com>